package me.faithfull.rugbydata;

/**
 * @author Will Faithfull
 */
public enum OffenceType {
    MISCONDUCT,
    ACT_CONTRARY_TO_GOOD_SPORTSMANSHIP,
    ANTI_DOPING,
    COMPETITION_APPEAL,
    DANGEROUS_CHARGING,
    DANGEROUS_PLAY_IN_SCRUM_RUCK_OR_MAUL,
    DANGEROUS_TACKLING,
    DISSENT,
    KICKING,
    PLAYING_AN_OPPONENT_WITHOUT_THE_BALL,
    PUNCHING_OR_STRIKING,
    RETALIATION,
    STAMPING_OR_TRAMPLING,
    TACKLING_THE_JUMPER_IN_THE_AIR,
    TIP_TACKLING,
    TRIPPING
}
